# Generated by Django 4.2 on 2024-03-30 11:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField(blank=True)),
                ('created', models.DateField(default='2024-03-30')),
                ('end_date', models.DateField(default='2024-03-30')),
                ('category', models.ForeignKey(default='general', on_delete=django.db.models.deletion.PROTECT, to='taskapp.category')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
