# Generated by Django 4.2 on 2024-04-01 06:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField(blank=True)),
                ('created', models.DateField(default='2024-04-01')),
                ('end_date', models.DateField(default='2024-04-01')),
                ('category', models.ForeignKey(default='general', on_delete=django.db.models.deletion.PROTECT, to='taskapp.category')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.DeleteModel(
            name='Task',
        ),
    ]
